version: '3.8'
services:
  nip05-verification:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sebastiansieber/nip05-verification:0.1
    container_name: nip05-verification
    ports:
      - 86:86
    networks:
      - proxy
    environment:
      - APP_PORT=$APP_PORT
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
networks:
  proxy:
    external: true

